config/routes.rb
Rails.application.routes.draw do
  resources :plantas do
    resources :experimentos
  end

  resources :experimentos do
    resources :plantas
  end

  resources :sistemas do
    resources :experimentos
  end

  devise_for :users
  resources :users

  get "home/index"
  get "home/mapa"

  root to: "home#index"
end

app/models/experimento.rb
class Experimento < ApplicationRecord
  extend FriendlyId
  friendly_id :nome, use: :slugged

  validates :nome, presence: true
  validates :fase, presence: true

  belongs_to :sistema
  has_many :experimento_plantas, dependent: :destroy
  has_many :plantas, through: :experimento_plantas
  accepts_nested_attributes_for :experimento_plantas, allow_destroy: true

  has_attached_file :imagem, styles: { medium: "360x360>", thumb: "180x180>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

  protected
    def should_generate_new_friendly_id?
      nome_changed?
    end

    def self.search(search)
      Experimento.joins(:sistema).where("experimentos.nome || sistemas.nome ILIKE ?", "%#{search}%")
    end
end

app/controllers/experimentos_controller.rb
class ExperimentosController < ApplicationController
  before_action :set_experimento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] { check_owner Experimento.friendly.find(params[:id]).sistema.user_id }
  before_action :load_sistemas, except: [:index]
  before_action :load_plantas, except: [:index]
  before_action :load_fases

  # GET /experimentos
  # GET /experimentos.json
  def index
    @experimentos = Experimento.all.order("nome ASC")

    if params[:search]
      @experimentos = Experimento.search(params[:search]).order("nome ASC")
    else
      if params[:sistema_id]
        @experimentos = Sistema.friendly.find(params[:sistema_id]).experimentos
      elsif params[:planta_id]
        @experimentos = Planta.friendly.find(params[:planta_id]).experimentos
      end
    end
  end

  # GET /experimentos/1
  # GET /experimentos/1.json
  def show
  end

  # GET /experimentos/new
  def new
    @experimento = Experimento.new
    @experimento.experimento_plantas.build
  end

  # GET /experimentos/1/edit
  def edit
    @plantas = Planta.all
    @experimento.experimento_plantas.build
  end

  # POST /experimentos
  # POST /experimentos.json
  def create
    @experimento = Experimento.new(experimento_params)

    respond_to do |format|
      if @experimento.save
        format.html { redirect_to @experimento, notice: "Experimento was successfully created." }
        format.json { render :show, status: :created, location: @experimento }
      else
        format.html { render :new }
        format.json { render json: @experimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experimentos/1
  # PATCH/PUT /experimentos/1.json
  def update
    respond_to do |format|
      if @experimento.update(experimento_params)
        format.html { redirect_to @experimento, notice: "Experimento was successfully updated." }
        format.json { render :show, status: :ok, location: @experimento }
      else
        format.html { render :edit }
        format.json { render json: @experimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experimentos/1
  # DELETE /experimentos/1.json
  def destroy
    @experimento.destroy
    respond_to do |format|
      format.html { redirect_to experimentos_url, notice: "Experimento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def load_sistemas
      @sistemas = {}
      if user_signed_in?
        @sistemas = current_user.admin ? Sistema.all : Sistema.where("user_id = #{current_user.id}")
      end
    end

    def load_plantas
      @plantas = Planta.all
    end

    def load_fases
      @fases = { "Planejamento" => "Planejamento", "Em Progresso" => "Em Progresso", "Finalizado" => "Finalizado" }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_experimento
      @experimento = Experimento.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experimento_params
      params.require(:experimento).permit(:nome, :descricao, :slug, :sistema_id, :imagem, :inicio, :fim, :fase, :experimento_id, planta_ids: [])
    end
end

app/helpers/experimentos_helper.rb
module ExperimentosHelper
end

app/views/experimentos/_form.html.erb
<% if @sistemas.count <= 0 %>
  <h3>Você Precisa Cadastrar pelo menos um Sistemas. <%= link_to "Cadastre Agora", new_sistema_path %></h3>
<% else %>
  <%= form_with(model: experimento, local: true, html: { multipart: true }) do |form| %>
    <% if experimento.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(experimento.errors.count, "error") %> encontrado(s):</h2>

        <ul>
        <% experimento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <%= form.label 'Sistema Associado', class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <% if (params[:sistema_id] && (current_user.admin? or Sistema.friendly.find(params[:sistema_id]).user.id == current_user.id)) %>
          <b>Sistema <%= Sistema.friendly.find(params[:sistema_id]).nome %></b>
          <%= form.hidden_field :sistema_id, value: Sistema.friendly.find(params[:sistema_id]).id %>
        <% else %>
          <%= form.collection_select(:sistema_id, @sistemas, :id, :nome,  {}, { class: "form-control" } ) %>
        <% end %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Nome", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.text_field :nome, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Fase", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.collection_select(:fase, @fases, :last, :first, {}, { class: "form-control" } ) %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Início", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.date_field :inicio, value: l(form.object.inicio || Date.today), placeholder: "DD/MM/YYYY", class: "form-control", data: { provide: "datepicker" } %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Fim", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.date_field :fim, value: l(form.object.fim || Date.today), placeholder: "DD/MM/YYYY", class: "form-control", data: { provide: "datepicker" } %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Descrição", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.text_field :descricao, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Imagem", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.file_field :imagem, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label 'Plantas Associadas', class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-10">
        <% if ! @plantas.empty? %>
          <%= form.collection_select(:planta_ids, @plantas, :id, :nome,  { include_hidden: false }, { class: "form-control", multiple: true } ) %>
        <% else %>
          <b>Não há Plantas Registradas. Deseja <%= link_to "Cadastrar?", new_planta_path, :target => "blank"%></b>
        <% end %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit t(:submit), class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/experimentos/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), experimentos_path, :class => "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_experimento_path, :class => "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "Editando #{@experimento.nome}", experimento_path(@experimento), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<%= render 'form', experimento: @experimento %>

app/views/experimentos/index.html.erb
<div class="search-box">
  <%= form_tag(experimentos_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], :size => 16 %>
    <%= submit_tag "Buscar", class: "btn btn-primary btn-sm" %>
  <% end %>
</div>
<br/><br/>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), experimentos_path, :class => "nav-link #{if (request.path == "/experimentos" && request.parameters["search"].blank?) then 'active' end }" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_experimento_path, :class => "nav-link" %>
    </li>
  <% end %>
  <% if request.path == "/sistemas/#{params[:sistema_id]}/experimentos" %>
    <li class="nav-item">
      <%= link_to 'Experimentos do ' + Sistema.friendly.find(params[:sistema_id]).nome, '#', :class => "nav-link active" %>
  </li>
  <% end %>
  <% if ! request.parameters["search"].blank? %>
    <li class="nav-item">
      <%= link_to 'Buscando por ' + request.parameters["search"], '#', :class => "nav-link active" %>
    </li>
  <% end %>
</ul>
<% if ! @experimentos.empty? %>
<div class="tab-content">
  <div class="tab-pane active"><br/>
    <table class="table table-responsive">
      <tbody>
        <% @experimentos.each_slice(5) do |p| %>
        <tr>
          <% p.each do |experimento| %>
            <td class="list">
              <div class="img-grid">
                <%= link_to image_tag(experimento.imagem.url(:thumb), :width => "180"), experimento_path(experimento) %>
              </div>
              <br/>
              <b><%= link_to experimento.nome, experimento_path(experimento) %></b>
              <br/>
              <%= link_to experimento.sistema.nome, sistema_path(experimento.sistema) %>
              <br/>
              <%= link_to 'Plantas Associadas: ' + experimento.plantas.count.to_s, experimento_plantas_path(experimento) %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% else %>
  <br/><br/><br/>
  <h3>Nenhum Registro Encontrado. Deseja <%= link_to 'Cadastrar?', new_experimento_path %></h3>
<% end %>

app/views/experimentos/new.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), experimentos_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:new), new_experimento_path, :class => "nav-link active" %>
  </li>
</ul>
<br/>
<%= render 'form', experimento: @experimento %>

app/views/experimentos/show.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), experimentos_path, :class => "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_experimento_path, :class => "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "#{t(:details)} #{@experimento.nome}", experimento_path(@experimento), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<div class="tab-content">
  <div class="tab-pane active">
    <dl class="row">
      <dt class="col-sm-3"><strong>Sistema Associado:</strong></dt>
      <dd class="col-sm-9"><%= link_to @experimento.sistema.nome, sistema_path(@experimento.sistema) %>&nbsp;</dd>

      <dt class="col-sm-3"><strong>Nome:</strong></dt>
      <dd class="col-sm-9"><%= @experimento.nome %>&nbsp;</dd>

      <dt class="col-sm-3"><strong>Início:</strong></dt>
      <dd class="col-sm-9"><%= @experimento.inicio %>&nbsp;</dd>

      <dt class="col-sm-3"><strong>Fim:</strong></dt>
      <dd class="col-sm-9"><%= @experimento.fim %>&nbsp;</dd>

      <dt class="col-sm-3"><strong>Fase:</strong></dt>
      <dd class="col-sm-9"><%= @experimento.fase %>&nbsp;</dd>
      <% if !@experimento.descricao.blank? %>
        <dt class="col-sm-3"><strong>Descrição:</strong></dt>
        <dd class="col-sm-9"><%= @experimento.descricao %>&nbsp;</dd>
      <% end %>
    </dl>

    <% if @experimento.plantas.count > 0 %>
    <div class="col-form-label-lg">Plantas Associadas</div>
    <div class="form-group row">
    <div class="tab-content" style="margin: auto;">
      <div class="tab-pane active"><br/>
        <table class="table table-responsive">
          <tbody>
            <% @experimento.plantas.each_slice(1) do |p| %>
            <tr>
              <% p.each do |planta| %>
                <td class="list">
                  <div class="img-grid">
                    <%= link_to image_tag(planta.imagem.url(:thumb), :height => "100"), planta_path(planta) %>
                  </div>
                  <br/>
                  <b><%= link_to planta.nome, planta_path(planta) %></b>
                </td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    </div>
    <% end %>

    <hr/>
    <% if user_signed_in? %>
      <% if current_user.admin? or @experimento.sistema.user.id == current_user.id %>
        <div class="form-actions">
          <%= link_to t(:back), experimentos_path, :class => 'btn btn-success'  %>
          <%= link_to t(:edit), edit_experimento_path(@experimento), :class => 'btn btn-warning' %>
          <%= link_to t(:destroy), experimento_path(@experimento), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) }, :class => 'btn btn-danger' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>