config/routes.rb
Rails.application.routes.draw do
  resources :plantas do
    resources :experimentos
  end

  resources :experimentos do
    resources :plantas
  end

  resources :sistemas do
    resources :experimentos
  end

  devise_for :users
  resources :users

  get "home/index"
  get "home/mapa"

  root to: "home#index"
end

app/models/sistema.rb
class Sistema < ApplicationRecord
  extend FriendlyId
  friendly_id :nome, use: :slugged

  validates :nome, presence: true
  validates :cidade, presence: true
  validates :uf, presence: true
  validates :imagem, presence: true

  has_many :experimentos
  has_many :plantas, through: :experimentos
  belongs_to :user

  # geocoded_by :localization
  # after_validation :geocode

  has_attached_file :imagem, styles: { medium: "360x360>", thumb: "180x180>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

  protected
    def should_generate_new_friendly_id?
      nome_changed?
    end

    def localization
      self.cidade + ", " + self.uf + ", " + self.cep
    end

    def self.search(search)
      where("nome || cidade ILIKE ?", "%#{search}%")
    end

    UF = [ "Acre" => "AC", "Alagoas" => "AL" ]

    def self.search(search)
      where("nome ILIKE ?", "%#{search}%")
    end
end

app/controllers/sistemas_controller.rb
class SistemasController < ApplicationController
  before_action :set_sistema, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] { check_owner Sistema.friendly.find(params[:id]).user_id }
  before_action :load_ufs, except: [:index]

  # GET /sistemas
  # GET /sistemas.json
  def index
    if params[:search]
      @sistemas = Sistema.search(params[:search]).order("nome ASC")
    else
      @sistemas = Sistema.all.order("nome ASC")
    end
  end

  # GET /sistemas/1
  # GET /sistemas/1.json
  def show
  end

  # GET /sistemas/new
  def new
    @sistema = Sistema.new
  end

  # GET /sistemas/1/edit
  def edit
  end

  # POST /sistemas
  # POST /sistemas.json
  def create
    @sistema = Sistema.new(sistema_params)
    @sistema.user_id = current_user.id

    respond_to do |format|
      if @sistema.save
        format.html { redirect_to @sistema, notice: "Sistema was successfully created." }
        format.json { render :show, status: :created, location: @sistema }
      else
        format.html { render :new }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sistemas/1
  # PATCH/PUT /sistemas/1.json
  def update
    respond_to do |format|
      if @sistema.update(sistema_params)
        format.html { redirect_to @sistema, notice: "Sistema was successfully updated." }
        format.json { render :show, status: :ok, location: @sistema }
      else
        format.html { render :edit }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sistemas/1
  # DELETE /sistemas/1.json
  def destroy
    @sistema.destroy
    respond_to do |format|
      format.html { redirect_to sistemas_url, notice: "Sistema was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sistema
      @sistema = Sistema.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sistema_params
      params.require(:sistema).permit(:nome, :slug, :descricao, :logradouro, :cidade, :uf, :cep, :latitude, :longitude, :user_id, :imagem)
    end
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/sistemas/_form.html.erb
<%= form_with(model: sistema, local: true, html: { multipart: true }) do |form| %>
  <% if sistema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sistema.errors.count, "error") %> encontrado(s):</h2>

      <ul>
      <% sistema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label "Nome", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= form.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Descrição", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= form.text_field :descricao, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Logradouro", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= form.text_field :logradouro, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Cidade", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= form.text_field :cidade, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "UF", class: "col-sm-2 col-form-label col-form-label-lg text-uppercase" %>
    <div class="col-sm-8">
      <%= form.collection_select(:uf, @ufs, :last, :first, {}, { class: "form-control" } ) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "CEP", class: "col-sm-2 col-form-label col-form-label-lg text-uppercase" %>
    <div class="col-sm-8">
      <%= form.text_field :cep, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Imagem", class: "col-sm-2 col-form-label col-form-label-lg" %>
    <div class="col-sm-8">
      <%= form.file_field :imagem, class: "form-control" %>
    </div>
  </div>

  <div class="col-form-label-lg">Localização</div>
  <div class="form-group row">
      <div id="map-sistema"></div>
  </div>

  <%= form.hidden_field :latitude, id: "latitude" %>
  <%= form.hidden_field :longitude, id: "longitude" %>

  <br/>

  <div class="actions">
    <%= form.submit t(:submit), class: "btn btn-primary" %>
  </div>

  <script>
    $( document ).ready(function() {
      lat = <%= request.safe_location.latitude %>;
      lon = <%= request.safe_location.longitude %>;

      <% if params[:action] == 'new' %>
        if (lat == 0.0 || lon == 0.0) {
          lat = -15.77835833463309;
          lon = -47.88219451904297;
        }
      <% else %>
          lat = <%= form.object.latitude %>;
          lon = <%= form.object.longitude %>;
      <% end %>

      var map = L.map('map-sistema', {zoomControl: false}).setView([lat, lon], 10);

      $(window).on("resize", function () { $("#map-sistema").width($(window).width()); map.invalidateSize(); }).trigger("resize");
      $(window).on("resize", function () { $("#map-sistema").height($(window).height()); map.invalidateSize(); }).trigger("resize");

      L.tileLayer('https://a.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: 'OpenStreetMap', maxZoom: 18,}).addTo(map);
      L.control.zoom({position:'topright'}).addTo(map);

      var Icon = L.icon({
                            iconUrl: '<%= image_url "leaflet/images/leaf-green.png" %>',
                            shadowUrl: '<%= image_url "leaflet/images/leaf-shadow.png" %>',
                            iconSize:     [38, 95],
                            shadowSize:   [50, 64],
                            iconAnchor:   [22, 94],
                            shadowAnchor: [4, 62],
                            popupAnchor:  [-3, -76]
                        });

      var marker = L.marker(new L.LatLng(lat, lon), { draggable: true, icon: Icon }).addTo(map);

      $('#latitude').val(lat);
      $('#longitude').val(lon);

      marker.on('dragend', function (e) {
        $('#latitude').val(marker.getLatLng().lat);
        $('#longitude').val(marker.getLatLng().lng);
      });

    });
  </script>
<% end %>

app/views/sistemas/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), sistemas_path, :class => "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_sistema_path, :class => "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "Editando #{@sistema.nome}", sistema_path(@sistema), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<%= render 'form', sistema: @sistema %>

app/views/sistemas/index.html.erb
<div class="search-box">
  <%= form_tag(sistemas_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], :size => 16 %>
    <%= submit_tag "Buscar", class: "btn btn-primary btn-sm" %>
  <% end %>
</div>
<br/><br/>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), sistemas_path, :class => "nav-link #{if (request.path == "/sistemas" && request.parameters["search"].blank?) then 'active' end }" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_sistema_path, :class => "nav-link" %>
    </li>
  <% end %>
  <% if ! request.parameters["search"].blank? %>
    <li class="nav-item">
      <%= link_to 'Buscando por ' + request.parameters["search"], '#', :class => "nav-link active" %>
    </li>
  <% end %>
</ul>
<% if ! @sistemas.empty? %>
<div class="tab-content">
  <div class="tab-pane active"><br/>
    <table class="table table-responsive">
      <tbody>
        <% @sistemas.each_slice(5) do |p| %>
        <tr>
          <% p.each do |sistema| %>
            <td class="list">
              <div class="img-grid">
                <%= link_to image_tag(sistema.imagem.url(:thumb), :width => "180"), sistema_path(sistema) %>
              </div>
              <br/>
              <b><%= link_to sistema.nome, sistema_path(sistema) %></b>
              <br/>
              <%= link_to 'Experimentos Registrados: ' + sistema.experimentos.count.to_s, sistema_experimentos_path(sistema) %>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% else %>
  <br/><br/><br/>
  <h3>Nenhum Registro Encontrado. Deseja <%= link_to 'Cadastrar?', new_sistema_path %></h3>
<% end %>

app/views/sistemas/new.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), sistemas_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:new), new_sistema_path, :class => "nav-link active" %>
  </li>
</ul>
<br/>
<%= render 'form', sistema: @sistema %>

app/views/sistemas/show.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? or current_user.id == @sistema.user_id %>
    <div class="form-actions" style="float: right;">
      <%= link_to "Cadastrar Experimento deste Sistema", new_sistema_experimento_path(@sistema), :class => 'btn btn-primary'  %>
    </div>
  <br/><br/><br/>
  <% end %>
<% end %>


<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), sistemas_path, :class => "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_sistema_path, :class => "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "#{t(:details)} #{@sistema.nome}", sistema_path(@sistema), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<div class="tab-content">
  <div class="tab-pane active">
    <dl class="row">
      <dt class="col-sm-3"><strong>Nome:</strong></dt>
      <dd class="col-sm-9"><%= @sistema.nome %>&nbsp;</dd>

      <% if @sistema.experimentos.count > 0 %>
        <dt class="col-sm-3"><strong>Experimentos:</strong></dt>
        <dd class="col-sm-9">
          <%= @sistema.experimentos.map {|experimento| link_to experimento.nome, experimento_path(experimento)}.join(", ").html_safe %>&nbsp;
        </dd>
        <% if @sistema.plantas.count > 0 %>
          <dt class="col-sm-3"><strong>Plantas:</strong></dt>
          <dd class="col-sm-9">
            <%= @sistema.plantas.map {|planta| link_to planta.nome, planta_path(planta)}.join(", ").html_safe %>&nbsp;
          </dd>
        <% end %>
      <% end %>

      <% if !@sistema.logradouro.blank? %>
        <dt class="col-sm-3"><strong>Logradouro:</strong></dt>
        <dd class="col-sm-9"><%= @sistema.logradouro %>&nbsp;</dd>
      <% end %>

      <dt class="col-sm-3"><strong>Cidade:</strong></dt>
      <dd class="col-sm-9"><%= @sistema.cidade %>&nbsp;</dd>

      <dt class="col-sm-3"><strong>UF:</strong></dt>
      <dd class="col-sm-9"><%= @sistema.uf %>&nbsp;</dd>

      <% if !@sistema.cep.blank? %>
        <dt class="col-sm-3"><strong>CEP:</strong></dt>
        <dd class="col-sm-9"><%= @sistema.cep %>&nbsp;</dd>
      <% end %>

      <% if !@sistema.descricao.blank? %>
        <dt class="col-sm-3"><strong>Descrição:</strong></dt>
        <dd class="col-sm-9"><%= @sistema.descricao %>&nbsp;</dd>
      <% end %>

      <dt class="col-sm-3"><strong>Responsável:</strong></dt>
      <dd class="col-sm-9"><%= @sistema.user.fullname %>&nbsp;</dd>
    </dl>

    <% if @sistema.latitude and @sistema.longitude %>
      <div class="col-form-label-lg">Localização</div>
      <div class="form-group row">
        <div id="map"></div>
      </div>

      <script>
        $( document ).ready(function() {
          var map = L.map('map').setView([<%= @sistema.latitude %>, <%= @sistema.longitude %>], 10);
          L.tileLayer('https://a.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: 'Mapas OBSAM - Leaflet - OpenStreetMap', maxZoom: 18,}).addTo(map);
          var Icon = L.icon({
                            iconUrl: '<%= image_url "leaflet/images/leaf-green.png" %>',
                            shadowUrl: '<%= image_url "leaflet/images/leaf-shadow.png" %>',
                            iconSize:     [38, 95],
                            shadowSize:   [50, 64],
                            iconAnchor:   [22, 94],
                            shadowAnchor: [4, 62],
                            popupAnchor:  [-3, -76]
                          });
          $(window).on("resize", function () { $("#map").width($(window).width() - 30); map.invalidateSize(); }).trigger("resize");
          $(window).on("resize", function () { $("#map").height($(window).height()); map.invalidateSize(); }).trigger("resize");

          L.marker([<%= @sistema.latitude %>, <%= @sistema.longitude %>], {icon: Icon}).addTo(map);
        });
      </script>
    <% end %>

    <hr/>
    <% if user_signed_in? %>
      <% if current_user.admin? or @sistema.user.id == current_user.id %>
        <div class="form-actions">
          <%= link_to t(:back), sistemas_path, :class => 'btn btn-success'  %>
          <%= link_to t(:edit), edit_sistema_path(@sistema), :class => 'btn btn-warning' %>
          <%= link_to t(:destroy), sistema_path(@sistema), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) }, :class => 'btn btn-danger' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>