config/routes.rb
Rails.application.routes.draw do
  resources :plantas do
    resources :experimentos
  end

  resources :experimentos do
    resources :plantas
  end

  resources :sistemas do
    resources :experimentos
  end

  devise_for :users
  resources :users

  get "home/index"
  get "home/mapa"

  root to: "home#index"
end

app/models/planta.rb
class Planta < ApplicationRecord
  extend FriendlyId
  friendly_id :nome, use: :slugged

  validates :nome, presence: true

  belongs_to :user
  has_many :experimento_plantas, dependent: :nullify
  has_many :experimentos, through: :experimento_plantas
  accepts_nested_attributes_for :experimento_plantas, allow_destroy: true

  has_attached_file :imagem, styles: { medium: "360x360>", thumb: "180x180>" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

  protected
    def should_generate_new_friendly_id?
      nome_changed?
    end

    def self.search(search)
      where("nome ILIKE ?", "%#{search}%")
    end
end

app/controllers/plantas_controller.rb
class PlantasController < ApplicationController
  before_action :set_planta, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] { check_owner Planta.friendly.find(params[:id]).user_id }

  # GET /plantas
  # GET /plantas.json
  def index
    @plantas = Planta.all.order("nome ASC")

    if params[:search]
      @plantas = Planta.search(params[:search]).order("nome ASC")
    else
      if params[:experimento_id]
        @plantas = Experimento.friendly.find(params[:experimento_id]).plantas
      end
    end
  end

  # GET /plantas/1
  # GET /plantas/1.json
  def show
  end

  # GET /plantas/new
  def new
    @planta = Planta.new
  end

  # GET /plantas/1/edit
  def edit
  end

  # POST /plantas
  # POST /plantas.json
  def create
    @planta = Planta.new(planta_params)
    @planta.user_id = current_user.id

    respond_to do |format|
      if @planta.save
        format.html { redirect_to @planta, notice: "Planta was successfully created." }
        format.json { render :show, status: :created, location: @planta }
      else
        format.html { render :new }
        format.json { render json: @planta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plantas/1
  # PATCH/PUT /plantas/1.json
  def update
    respond_to do |format|
      if @planta.update(planta_params)
        format.html { redirect_to @planta, notice: "Planta was successfully updated." }
        format.json { render :show, status: :ok, location: @planta }
      else
        format.html { render :edit }
        format.json { render json: @planta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantas/1
  # DELETE /plantas/1.json
  def destroy
    @planta.destroy
    respond_to do |format|
      format.html { redirect_to plantas_url, notice: "Planta was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planta
      @planta = Planta.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planta_params
      params.require(:planta).permit(:nome, :descricao, :slug, :user_id, :imagem)
    end
end

app/helpers/plantas_helper.rb
module PlantasHelper
end

app/views/plantas/_form.html.erb
  <%= form_with(model: planta, local: true, html: { multipart: true }) do |form| %>
    <% if planta.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(planta.errors.count, "error") %> encontrado(s):</h2>

        <ul>
        <% planta.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <%= form.label "Nome", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.text_field :nome, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Descrição", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.text_field :descricao, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label "Imagem", class: "col-sm-2 col-form-label col-form-label-lg" %>
      <div class="col-sm-8">
        <%= form.file_field :imagem, class: "form-control" %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit t(:submit), class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/plantas/edit.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), plantas_path, :class => "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_planta_path, :class => "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "Editando #{@planta.nome}", planta_path(@planta), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<%= render 'form', planta: @planta %>

app/views/plantas/index.html.erb
<div class="search-box">
  <%= form_tag(plantas_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], :size => 16 %>
    <%= submit_tag "Buscar", class: "btn btn-primary btn-sm" %>
  <% end %>
</div>
<br/><br/>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), plantas_path, :class => "nav-link #{if (request.path == "/plantas" && request.parameters["search"].blank?) then 'active' end }" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_planta_path, :class => "nav-link" %>
    </li>
  <% end %>
  <% if request.path != "/plantas" %>
    <li class="nav-item">
      <%= link_to 'Plantas do ' + Experimento.friendly.find(params[:experimento_id]).nome, '#', :class => "nav-link active" %>
  </li>
  <% end %>
  <% if ! request.parameters["search"].blank? %>
    <li class="nav-item">
      <%= link_to 'Buscando por ' + request.parameters["search"], '#', :class => "nav-link active" %>
    </li>
  <% end %>
</ul>
<% if ! @plantas.empty? %>
<div class="tab-content">
  <div class="tab-pane active"><br/>
    <table class="table table-responsive">
      <tbody>
        <% @plantas.each_slice(5) do |p| %>
        <tr>
          <% p.each do |planta| %>
            <td class="list">
              <div class="img-grid">
                <%= link_to image_tag(planta.imagem.url(:thumb), :width => "180"), planta_path(planta) %>
              </div>
              <br/>
              <b><%= link_to planta.nome, planta_path(planta) %></b>
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% else %>
  <br/><br/><br/>
  <h3>Nenhum Registro Encontrado. Deseja <%= link_to 'Cadastrar?', new_planta_path %></h3>
<% end %>

app/views/plantas/new.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), plantas_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:new), new_planta_path, :class => "nav-link active" %>
  </li>
</ul>
<br/>
<%= render 'form', planta: @planta %>

app/views/plantas/show.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(:all), plantas_path, :class => "nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to t(:new), new_planta_path, :class => "nav-link" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "#{t(:details)} #{@planta.nome}", planta_path(@planta), :class => "nav-link active" %>
  </li>
</ul>

<br/>

<div class="tab-content">
  <div class="tab-pane active">
    <%= image_tag(@planta.imagem.url(:medium), :height => "150px") %><br/><br/>
    <dl class="row">
      <dt class="col-sm-3"><strong>Nome:</strong></dt>
      <dd class="col-sm-9"><%= @planta.nome %>&nbsp;</dd>

      <dt class="col-sm-3"><strong>Descrição:</strong></dt>
      <dd class="col-sm-9"><%= @planta.descricao %>&nbsp;</dd>

      <% if @planta.experimentos.count > 0 %>
        <dt class="col-sm-3"><strong>Experimentos:</strong></dt>
        <dd class="col-sm-9">
         <%= @planta.experimentos.map {|experimento| link_to experimento.nome, experimento_path(experimento)}.join(", ").html_safe %>&nbsp;
        </dd>
      <% end %>
    </dl>

    <hr/>
    <% if user_signed_in? %>
      <% if current_user.admin? or @planta.user.id == current_user.id %>
        <div class="form-actions">
          <%= link_to t(:back), plantas_path, :class => 'btn btn-success'  %>
          <%= link_to t(:edit), edit_planta_path(@planta), :class => 'btn btn-warning' %>
          <%= link_to t(:destroy), planta_path(@planta), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) }, :class => 'btn btn-danger' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>