config/routes.rb
Rails.application.routes.draw do
  resources :plantas do
    resources :experimentos
  end

  resources :experimentos do
    resources :plantas
  end

  resources :sistemas do
    resources :experimentos
  end

  devise_for :users
  resources :users

  get "home/index"
  get "home/mapa"

  root to: "home#index"
end

app/views/layouts/_alert.html.erb
        <% if notice %>
          <div class="alert alert-info fade in" role="alert">
            <%= notice %>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger fade in" role="alert">
            <%= alert %>
          </div>
        <% end %>

app/views/layouts/_footer.html.erb
    <br/>
    <footer class="footer">
      <div class="container">
        <span class="text-muted">
          <a href="https://gitlab.com/ITBio3/safbd" target="_blank">SAFBD (beta)</a> - Licenciado sobre a GPLv3
        </span>
      </div>
    </footer>

app/views/layouts/_main.html.erb
<div class="container">
      <div class="starter-template">
        <% if notice or alert%>
          <%= render 'layouts/alert' %>
        <% end %>
        <%= yield %>
      </div>
    </div>

app/views/layouts/_menu.html.erb
  <nav class="navbar navbar-toggleable-md navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        &#9776;
      </button>

      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <%= link_to("Início", root_path, :class => "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link_to("Mapa", home_mapa_path, :class => "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link_to("Sistemas", sistemas_path, :class => "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link_to("Experimentos", experimentos_path, :class => "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link_to("Plantas", plantas_path, :class => "nav-link") %>
          </li>

          <% if current_user %>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to("Usuários", users_path, :class => "nav-link") %>
              </li>
            <% end %>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to("#{t(:logout)}", destroy_user_session_path, :method => :delete, :class => "nav-link") %>
            </li>

            <li class="nav-item">
              <%= link_to "(#{current_user.email})", user_path(current_user), :class => "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to(t(:login), new_user_session_path, :class => "nav-link") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= CONFIG['lang'] %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="<%= image_url "favicon.ico" %>">

    <title><%= CONFIG['title'] %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/menu' %>
    <%= render 'layouts/main' %>
    <%= render 'layouts/footer' %>

  </body>
</html>